apiVersion: apps/v1
kind: Deployment
metadata:
  name: monster-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monster-app
  template:
    metadata:
      labels:
        app: monster-app
    spec:
      containers:
      - name: monster-app
        image: 642341975645.dkr.ecr.us-east-1.amazonaws.com/monster-image-repo:8ffe29dd53656eee5090ca150dc5a6ab1619d5ea-133
        ports:
        - containerPort: 443

